# Generated by Django 4.2.4 on 2023-09-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
