# Generated by Django 4.2.4 on 2023-09-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0002_location_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="qr_code",
            field=models.FileField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
