# Generated by Django 4.2.5 on 2023-10-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register_app", "0003_role_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
                null=True,
            ),
        ),
    ]
