# Generated by Django 4.2.5 on 2023-10-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register_app", "0004_alter_project_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_manager_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_manager_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_url",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="site_manager_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="site_manager_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
