# Generated by Django 4.2.5 on 2023-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register_app", "0005_alter_project_project_manager_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
